import java.time.Instant;
import java.util.Date;
import java.util.Set;
import java.util.UUID;

/**
 * This class represents messages that client and server exchange.
 *
 * There are 6 possible kinds of messages
 * (all represented by this type because I don't want 6 tiny classes).
 *
 * The class has constructors for only 4 of those,
 * because the first two kinds are always generated by clients.
 * We need to be able to serialize and deserialize those messages, however,
 * therefore they are included in this combined type.
 *
 * ---- Messages generated by clients: ----
 *
 * // broadcasted
 * type: "message",
 * text: "some text typed in by the user",
 * id: clientID,
 * date: 2349875459,
 * username: "someUsername" // added by the server
 *
 * // broadcasted
 * type: "username"
 * username: "someUsername",
 * id: clientID,
 * date: 2349875459
 *
 *  ---- Messages generated by server: ----
 *
 * type: "rejectusername",
 * username: "usernameGeneratedByServerAndEnsuredUnique"
 * id: clientID
 *
 * type: "id",
 * id: clientID
 *
 * // broadcasted
 * type: "userlist",
 * users: []
 *
 * // broadcasted
 * type: "userleft",
 * username: "username",
 * users: [],
 * id: clientID,
 * date: 2349875459
 */
public class Message {
    public String type;
    public UUID id;
    public long date; // represents the amount of ms passed since Jan 1, 1970
    public String username;
    public Set<String> users;
    public String text;

    public Message(UUID id) {
        this.type = "id";
        this.id = id;
    }

    public Message(Set<String> users) {
        this.type = "userlist";
        this.users = users;
    }

    public Message(String username, UUID id) {
        this.type = "rejectusername";
        this.username = username;
        this.id = id;
    }

    public Message(String username, Set<String> userlist) {
        this.type = "userleft";
        this.username = username;
        this.users = userlist;
        this.date = Instant.now().toEpochMilli();
    }
}
